config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'users' => 'users#index'

  get 'users/new' => 'users#new', as: :new_user

  post 'users/' => 'users#create'

  get 'users/:id' => 'users#show', as: :user

  get 'users/:id/edit' => 'users#edit', as: :edit_user

  patch 'users/:id' => 'users#update'

  delete 'users/:id' => 'users#destroy'

  root 'products#index'

  get 'products/new' => 'products#new', as: :new_product

  post 'products/' => 'products#create'

  get 'products/:id' => 'products#show', as: :product

  get 'cart' => 'cart#index'

  get 'cart/clear' => 'cart#clearCart'

  get 'cart/:id' => 'cart#add'

  get 'products/:id/edit' => 'products#edit', as: :edit_product
  
  patch 'products/:id' => 'products#update'

  delete 'products/:id' => 'products#destroy'

  get 'about' => 'static_pages#about'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	belongs_to :products
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :cart
	has_attached_file :image, styles: { small: "100x100", med: "300x300", large: "600x600" },:default_url => '/images/missing.png'
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :password, presence: true, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :log_in, :logged_in, :authenticate
  	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def authenticate
    unless logged_in?
      flash[:notice] = "You must be logged in"
      redirect_to login_url
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_action :authenticate

	def add
		id = params[:id]
			if session[:cart] then
				cart = session[:cart]
			else
				session[:cart] = {}
				cart = session[:cart]
			end
			if cart[id] then
				cart[id] = cart[id] + 1
			else
				cart[id] = 1
			end
			redirect_to :action => :index
		end

	def clearCart
		session[:cart] = nil
		redirect_to :action => :index
	end

	def index
		if session[:cart] then
			@cart = session[:cart]
		else
			@cart = {}
		end
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
		# Amount in cents
		@amount = 500

		customer = Stripe::Customer.create(
			:email => params[:stripeEmail],
			:source => params[:stripeToken]
			)

		charge = Stipe::Charge.create(
			:customer => customer.id,
			:amount => @amount,
			:description => 'Rails Stripe customer',
			:currency => 'usd'
			)

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to new_charge_path
	end
	
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
  	@order = current_order
  	@order_item = @order.order_items.new(order_item_params)
  	@order.save
  	session[:order_id] = @order.id
  end

  def update
  	@order = current_order
  	@order_item = @order.order_item.find(params[:id])
  	@order_item.update_attributes(order_item_params)
  	@order_items = @order.order_items
  end

  def destroy
  	@order = current_order
  	@order_item = @order.order_items.find(params[:id])
  	@order_item.destroy
  	@order_items = @order.order_items
  end

  private
  	def order_item_params
  		params.require(:order_item).permit(:quantity, :product_id)
  	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to product_path(@product)
      else
        render :new
      end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :category, :quantity, :title, :body, :image)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate

  def index
    @users = User.all
    if @user != current_user
      redirect_to login_path
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])

  end

  def create
  	@user = User.new(user_params)
  		if @user.save
        log_in @user
        flash[:success] = "Welcome to the Sample App!"
  			redirect_to root_path
  		else
  			render :new
  		end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		redirect_to user_path(@user)
  	else
  		render :edit
  	end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def cart
    @products = Product.all
  end

  private
  	def user_params
  		params.require(:user).permit(:email, :password, :password_confirmation, :carts_attributes => [:id, :price_total, :product_id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/index.html.erb
<div class="container-fluid">
	<h1 class="text-center">Your Cart</h1>
	<br><br><br>
	<div class="table-responsive">
		<% total = 0 %>
		<table class="table">
			<% @cart.each do | id, quantity | %>
			<tr>
				<% product = Product.find_by_id(id) %>
					<td><%= link_to product.name, product %></td>
					<td><%= number_to_currency(product.price, :unit => '$') %></td>
					<td>Quantity: <%= quantity %></td>
			</tr>
				<% total += quantity * product.price %>
			<% end %>
		</table>
	</div>
	<div class="text-right">
	<p><strong>Total: <%= number_to_currency(total, :unit => '$') %></strong></p>
	<% if @cart.empty? %>
		<p>Your Cart is currently empty.</p>
	<% else %>
		<%= link_to 'Empty Cart', cart_clear_path, :class => "btn btn-primary" %>
	<% end %>
	</div>
</div>

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>
<a href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_7fs0JK0eBSPF2Kt3uFi87n1cpS2rh8B0&scope=read_write"</a>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

<a href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_7fs0JK0eBSPF2Kt3uFi87n1cpS2rh8B0&scope=read_write"</a>