config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'users' => 'users#index'

  get 'users/new' => 'users#new', as: :new_user

  post 'users/' => 'users#create'

  get 'users/:id' => 'users#show', as: :user

  get 'users/:id/edit' => 'users#edit', as: :edit_user

  patch 'users/:id' => 'users#update'

  delete 'users/:id' => 'users#destroy'

  root 'products#index'

  get 'products/new' => 'products#new', as: :new_product

  post 'products/' => 'products#create'

  get 'products/:id' => 'products#show', as: :product

  get 'cart' => 'cart#index'

  get 'cart/clear' => 'cart#clearCart'

  get 'cart/:id' => 'cart#add'

  get 'products/:id/edit' => 'products#edit', as: :edit_product
  
  patch 'products/:id' => 'products#update'

  delete 'products/:id' => 'products#destroy'

  get 'about' => 'static_pages#about'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	belongs_to :products
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :cart
	has_attached_file :image, styles: { small: "100x100", med: "300x300", large: "600x600" },:default_url => '/images/missing.png'
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :password, presence: true, confirmation: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_action :authenticate

	def add
		id = params[:id]
			if session[:cart] then
				cart = session[:cart]
			else
				session[:cart] = {}
				cart = session[:cart]
			end
			if cart[id] then
				cart[id] = cart[id] + 1
			else
				cart[id] = 1
			end
			redirect_to :action => :index
		end

	def clearCart
		session[:cart] = nil
		redirect_to :action => :index
	end

	def index
		if session[:cart] then
			@cart = session[:cart]
		else
			@cart = {}
		end
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
		# Amount in cents
		@amount = 500

		customer = Stripe::Customer.create(
			:email => params[:stripeEmail],
			:source => params[:stripeToken]
			)

		charge = Stipe::Charge.create(
			:customer => customer.id,
			:amount => @amount,
			:description => 'Rails Stripe customer',
			:currency => 'usd'
			)

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to new_charge_path
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate

  def index
    @users = User.all
    if @user != current_user
      redirect_to login_path
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])

  end

  def create
  	@user = User.new(user_params)
  		if @user.save
        log_in @user
        flash[:success] = "Welcome to the Sample App!"
  			redirect_to root_path
  		else
  			render :new
  		end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		redirect_to user_path(@user)
  	else
  		render :edit
  	end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def cart
    @products = Product.all
  end

  private
  	def user_params
  		params.require(:user).permit(:email, :password, :password_confirmation, :carts_attributes => [:id, :price_total, :product_id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
      <div class="navbar-header">
        <%= link_to image_tag("logo_small.png"), root_path, class: "navbar-brand logo" %>
      </div>
      <li><%= link_to "Home",   root_path %></li>
        
          <li><%= link_to "About", about_path %></li>
          
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if logged_in? %>
          <li><%= link_to "Logout", logout_path %></li>
          <li><%= link_to "Edit My Profile", edit_user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      <li><%= link_to "", cart_path, :class => "glyphicon glyphicon-shopping-cart" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatherineLenoreApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>